version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@4.0.1

jobs:
  test:
    docker:
      - image: circleci/ruby:2.5.1
        environment:
          DATABASE_URL: postgres://postgres@localhost/laa-common-platform-connector_test
      - image: circleci/postgres:11.5-alpine
        environment:
          POSTGRES_DB: laa-common-platform-connector_test
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Database Setup
          command: |
            bundle exec rake db:migrate

      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"

            bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format progress \
              $TEST_FILES

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

workflows:
 version: 2
 test_and_build:
    jobs:
      - test
      - aws-ecr/build_and_push_image:
          requires:
            - test
          repo: laa-crime-apps-team/laa-common-platform-connector
          tag: ${CIRCLE_SHA1}
